// <auto-generated />
namespace ProjectTwo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class listSeenColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(listSeenColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202201210406538_listSeenColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
